@Api_HostAddress = http://localhost:5027

GET {{Api_HostAddress}}/api/usuarios?pageNumber=1&pageSize=10
Accept: application/json

###

GET {{Api_HostAddress}}/api/usuarios?pageNumber=0&pageSize=101
Accept: application/json

###

GET {{Api_HostAddress}}/api/usuarios/00000000-0000-0000-0000-000000000000
Accept: application/json

###

POST {{Api_HostAddress}}/api/usuarios
Content-Type: application/json

{
  "nombre": "Sebastian",
  "apellido": "Prueba",
  "email": "SEBASTIAN.PRUEBA@example.com"
}

###

PUT {{Api_HostAddress}}/api/usuarios/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "nombre": "Sebastian",
  "apellido": "Actualizado",
  "email": "sebastian.actualizado@example.com"
}

###

DELETE {{Api_HostAddress}}/api/usuarios/00000000-0000-0000-0000-000000000000
Accept: application/json

###
